version: '3.8'

services:
  # Zookeeper (required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Postgres database
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=flight
      - POSTGRES_PASSWORD=flight
      - POSTGRES_DB=flightdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Flight data producer
  producer:
    build: ./FlightProducerService
    depends_on:
      - kafka

  # Flight data consumer
  consumer:
    build: ./FlightConsumerService
    depends_on:
      - kafka
      - postgres

  # GraphQL API
  graphql:
    build: ./FlightGraphQLService
    ports:
      - "5000:80"
    depends_on:
      - postgres

volumes:
  pgdata:
