services:
  # Zookeeper (required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - flightnet
    ports:
      - "2181:2181"

  # Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - flightnet
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postgres database
  postgres:
    image: postgres:16
    container_name: flight-postgres
    environment:
      - POSTGRES_USER=flight
      - POSTGRES_PASSWORD=flight
      - POSTGRES_DB=flightdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flightnet

  # Flight data producer
  producer:
    build: ./FlightProducerService
    networks:
      - flightnet
    depends_on:
      - kafka

  # Flight data consumer
  consumer:
    build: ./FlightConsumerService
    networks:
      - flightnet
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started

  # GraphQL API
  flightgraphql:
    build: ./FlightGraphQLService
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - flightnet

volumes:
  pgdata:

networks:
  flightnet:
    driver: bridge
